import type { CapacitorConfig } from '@capacitor/cli';

/**
 * AUTO-GENERATED by scripts/sync-tunnel-url.js
 * Do not edit manually — run `npm run cap:sync:tunnel` to regenerate.
 *
 * Tunnel URL : https://removal-aberdeen-brochure-impact.trycloudflare.com
 * Generated  : 2026-09-30T07:21:03.019Z
 *
 * This URL works on ANY network (4G, 5G, any Wi-Fi).
 * The tunnel securely forwards traffic to your local Next.js server.
 */
const config: CapacitorConfig = {
  appId: 'com.assistance.ai',
  appName: 'Personal Agent',
  webDir: 'public',
  server: {
    // Public Cloudflare tunnel URL — works on all networks globally
    url: 'https://removal-aberdeen-brochure-impact.trycloudflare.com',
    cleartext: false,
    androidScheme: 'https',
  },
  plugins: {
    SplashScreen: {
      launchShowDuration: 2000,
      backgroundColor: '#0c111d',
      showSpinner: false,
    },
  },
};

export default config;
